services:
  splitter:
    build: 
      context: ./splitter
      platforms:
        - linux/amd64
    image: mapreduce-splitter:latest
    platform: linux/amd64
    ports:
      - "8081:8080"
    
  mapper:
    build: 
      context: ./mapper
      platforms:
        - linux/amd64
    image: mapreduce-mapper:latest
    platform: linux/amd64
    ports:
      - "8082:8080"
    
  reducer:
    build: 
      context: ./reducer
      platforms:
        - linux/amd64
    image: mapreduce-reducer:latest
    platform: linux/amd64
    ports:
      - "8083:8080"